### ISSUE TITLE
WalletApp crash when manually start the synchronisation

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-android#163]
## Describe the bug
When manually start the synchronisation, the app will crash

## Steps to reproduce the issue
1. go to settings
2. click on "update recovation state"

![image](https://user-images.githubusercontent.com/81565834/154992955-befbd479-ff19-40e9-9bfe-f24187ab1358.png)

## Technical details
- Pixel 3a XL
- Android 12

**Comment by kerstin-oppermann-tsi** [comment]
After fresh install of the wallet app reloading works fine several times.

But after claiming certificate, no matter if a revoked one or not, the next reloading crashes the app.

**Comment by kerstin-oppermann-tsi** [comment]
Issue is fixed with wallet 1.2.8.tst (39). Please retest @michawol or @RalicaY

**Comment by RalicaY** [comment]
The issue persists on my end, also with the latest version 1.2.8.tst (39)  I have attached the logs.
[tan_wallet_crash_log.txt](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/files/8118070/tan_wallet_crash_log.txt)

**Comment by oleksandrsarapulovgl** [comment]
There was an issue from BE side, I added fix to handle that. Could you please check 1.2.8.tst (40)?

@RalicaY

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl 
It looks good! I could produce no crash. Test is successful. Thank You very much!
